export const FACEBOOK_INIT_START = 'FACEBOOK_INIT_START';
export const FACEBOOK_INIT_COMPLETE = 'FACEBOOK_INIT_COMPLETE';

export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_RECEIVE = 'FACEBOOK_LOGIN_RECEIVE';
export const FACEBOOK_LOGIN_ERROR   = 'FACEBOOK_LOGIN_ERROR';

export const FACEBOOK_LOGOUT_REQUEST = 'FACEBOOK_LOGOUT_REQUEST';
export const FACEBOOK_LOGOUT_COMPLETE = 'FACEBOOK_LOGOUT_COMPLETE';

export const FACEBOOK_USER_INFO_REQUEST = 'FACEBOOK_USER_INFO_REQUEST';
export const FACEBOOK_USER_INFO_RECEIVED = 'FACEBOOK_USER_INFO_RECEIVED';
export const FACEBOOK_USER_INFO_ERROR = 'FACEBOOK_USER_INFO_ERROR';
