export const FOOD_REQUEST = 'FOOD_REQUEST';
export const FOOD_RECEIVE = 'FOOD_RECEIVE';
export const FOOD_ERROR   = 'FOOD_ERROR';

export const NEARBY_FOODS_REQUEST = 'NEARBY_FOODS_REQUEST';
export const NEARBY_FOODS_RECEIVE = 'NEARBY_FOODS_RECEIVE';
export const NEARBY_FOODS_ERROR   = 'NEARBY_FOODS_ERROR';
