export const FOOD_REQUEST = 'FOOD_REQUEST';
export const FOOD_RECEIVE = 'FOOD_RECEIVE';
export const FOOD_ERROR   = 'FOOD_ERROR';

export const FOOD_POSTING = 'FOOD_POSTING';
export const FOOD_POSTED  = 'FOOD_POSTED';
export const FOOD_POST_ERROR = 'FOOD_POST_ERROR';

export const NEARBY_FOODS_REQUEST = 'NEARBY_FOODS_REQUEST';
export const NEARBY_FOODS_RECEIVE = 'NEARBY_FOODS_RECEIVE';
export const NEARBY_FOODS_ERROR   = 'NEARBY_FOODS_ERROR';
